export const routes = {
    home: '/',
    londonBridge: '/london-bridge',
    soho: '/soho',
    hammersmith: '/hammersmith',
    chelsea: '/chelsea',
    farringdon: '/farringdon',
    shoreditch: '/shoreditch',
    clapham: '/clapham',
    brixton: '/brixton',
    about: '/about',
    faq: '/faq',
    events: '/events',
    sitemap: '/sitemap',
    personalMatchmaking: '/matches',
    blog: '/blog',
    contact: '/contact',
    profile: '/profile',
    account: '/account',
    login: '/login',
    signUp: '/sign-up',
    passwordReset: '/reset-password',
    admin: '/admin',
    adminEvents: '/admin/events',
    adminBlogs: '/admin/blogs',
    adminUsers: '/admin/users',
    speeddating: '/london/speed-dating',
    adminSubscribers: '/admin/subscribers',
    adminRefund: '/admin/refund',
    offers: '/admin/offers',
    messages: '/messages',
    myMessages: '/my-messages',
    matches: '/matches',
    tos: '/terms-of-service',
    membership: '/membership',
    privacyPolicy: '/privacy-policy',
    pastEvents: '/pastEvents',
    thankyou: '/thankyou',
    // firstDate5Ideas: '/blog/first-date-gifts-5-ideas',
    // riseAndFallOfDatingApps: '/blog/the-rise-and-fall-of-dating-apps',
    // goodSeducationSkills: '/blog/how-good-are-seducation-skills',
    // datingOver50: '/blog/dating-over-50-guide',
    // speedDatingTipsWomen: '/blog/speed-dating-tips-for-women',
    // datingTrends: '/blog/dating-trends',
    // escapeFriendZone: '/blog/how-escape-friend-zone',
    // speedDatingWithTrueDating: '/blog/speed-dating-with-true-dating',
    // irrationalFears: '/blog/5-irrational-fears-beliefs-about-no-contact',
    // interestingDatingMessages: '/blog/how-to-be-interesting-on-dating-messages',
    // greatFirstImpression: '/blog/how-to-make-a-great-first-impression-on-a-date',
    // whyDatingApps: '/blog/why-dating-apps-must-put-user-safety',
    // commonDatingMistakes: '/blog/common-speed-dating-mistakes',
    // datingInCovidWorld: '/blog/dating-in-covid-vaccinated-world',
    // waysToUpDatingGame: '/blog/10-ways-to-up-your-dating-game',
    // mostOutOfDating: '/blog/quick-tips-for-speed-dating',
    // speedDatingMen: '/blog/speed-dating-tips-for-men',
    // notReciprocatingInterest: '/blog/not-reciprocating-romantic-interest',
    // bestDatingTipsWomen: '/blog/best-dating-tips-for-women-over-40',
    // commonPhrases: '/blog/common-phrases-that-block-love',
    // valentine2023: '/blog/origins-and-meaning-of-valentines-day',
    // valentine2023Redirect: '/blog/valentines-day-2023-origins-meaning-and-more',
    matureDating: '/uk-mature-dating',
    christianDating: '/christian-dating',
    gayDating: '/gay-dating',
    // loveHoroscope: '/blog/love-horoscope-for-2023',
    // journeyToFindingRomance: '/blog/journey-to-finding-romance-and-friendship-in-london',
    // healBrokenHeart: '/blog/how-to-heal-a-broken-heart',
    // signsFallingInLove: '/blog/how-do-you-know-you-love-someone',
    // romanticPlacesInLondon: '/blog/romantic-places-in-london',
    // firstDateQuestions: '/blog/first-date-questions-and-conversation-starters',
    // meetingParents: '/blog/tips-for-meeting-the-partners-parents-first-time',
};